language: csharp
dist: xenial
sudo: false
dotnet: 2.2.103
mono:
- 5.18.1
- latest
matrix:
  fast_finish: true
addons:
  apt:
    packages:
    - libzmq3-dev
services:
- docker
env:
  global:
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - TMPDIR=/tmp
  - secure: M3SRlsAT2fDKrbZatBXwrN8Ta6L4iB8XqBgaMJqoJab1ptZRSjdYCwtk7II/l1dfe3ayI0P/NfKyh2oCmjKVtN2eLD3o/zF9pg8iuQu4sIEP20SJLLqyPT6fDnOE5Y6aZx9jXEEXshXmFlo7ot0HlbJkpFwfFbQ+tdMwq8HqzG4=
script:
- travis_wait make
after_success:
- make ci_push
notifications:
  email: false
