version: '3'
services:
  influxdb:
    image: influxdb:1.4 # https://hub.docker.com/_/influxdb/
    ports:
    - 8086:8086 # http api
    - 8083:8083 # admin if
    - 2003:2003 # graphite ingestion
    volumes:
    - ./tools/data/influxdb:/var/lib/influxdb

  # https://github.com/influxdata/telegraf
  telegraf:
    image: telegraf:latest
    links:
    - influxdb
    volumes:
    - ./tools/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  # https://github.com/influxdata/telegraf
  grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    environment:
    - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    links:
    - influxdb

  # https://www.rabbitmq.com/
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
    - 5672:5672 # AMQP
    - 15672:15672 # HTTP mgmt

# References:
# - https://github.com/nicolargo/docker-influxdb-grafana

# Run:
# - docker-compose up -d
