apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "logary-site.fullname" . }}-stripe
  namespace: {{ .Release.Namespace | default "logary" | quote }}
  labels:
    app.kubernetes.io/name: {{ include "logary-site.name" . }}
    helm.sh/chart: {{ include "logary-site.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  secretKey: {{ .Values.stripeSecretKey | default "c2tfdGVzdF93S2hkVFhqc1BGSTFZY0lTd3h6WHgzRVA=" | quote }}