{{- if .Values.stubEtc }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rutta.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rutta.name" . }}
    helm.sh/chart: {{ include "rutta.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

type: Opaque
data:
  {{- with .Values.etc.data -}}
    {{ toYaml . | nindent 4 }}
  {{- end }}
  example.json: |
    CHANGE_ME
{{- end }}